default:
  tags: [docker]

image: registry.gitlab.utc.fr/syrousse/guv:latest

stages:
  - test
  - deploy
  - publish

cache:
  paths:
    - .tox

before_script:
  - pip install tox

test:
  stage: test
  script:
    - tox -e tests -- --basetemp=.tox/tests/tmp -v -rA --cache-clear

pages:
  stage: deploy
  script:
    - tox -e docs -- -W
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

package:
  stage: publish
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
