default:
  tags: [docker]

image: registry.gitlab.utc.fr/syrousse/guv:latest

stages:
  - test
  - deploy
  - publish

variables:
  UV_PUBLISH_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  UV_PUBLISH_USERNAME: "gitlab-ci-token"
  UV_PUBLISH_PASSWORD: "${CI_JOB_TOKEN}"

cache:
  paths:
    - .venv

before_script:
  - pip install uv

test:
  stage: test
  script:
    - uv run pytest -v -rA --cache-clear

pages:
  stage: deploy
  script:
    - uv run --group doc sphinx-build --builder html --fail-on-warning docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

package:
  stage: publish
  script:
    - uv build
    - uv publish
