default:
  tags: [docker]

image: registry.gitlab.utc.fr/syrousse/guv:latest

stages:
  - test
  - deploy

cache:
  paths:
    - .tox

before_script:
  - pip install tox

test:
  stage: test
  script:
    - tox -e tests

pages:
  stage: deploy
  script:
    - tox -e docs
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
