default:
  tags: [docker]

image: registry.gitlab.utc.fr/syrousse/guv:latest

stages:
  - test
  - deploy
  - publish

cache:
  paths:
    - .venv

before_script:
  - pip install uv

test:
  stage: test
  script:
    - uv run --with '.[test]' pytest -v -rA --cache-clear

pages:
  stage: deploy
  script:
    - uv run --with '.[doc]' sphinx-build --builder html --fail-on-warning docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

package:
  stage: publish
  script:
    - uv build
    - uv publish --index ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi --username gitlab-ci-token --password ${CI_JOB_TOKEN}
